### ISSUE TITLE
签名部分时按照微信文档吗？

### ISSUE THREAD

**Issue by YuiFx** [QuTianbai/WXPay#1]
微信支付文档中的签名是Md5，url中是sha1

**Comment by YuiFx** [comment]
能否分享下签名的逻辑

**Comment by QuTianbai** [comment]
您好，我没有参照微信文档，请问您是？

**Comment by QuTianbai** [comment]
可以加我QQ，932462423详聊

**Comment by QuTianbai** [comment]
通过URL截取微信SDK发送给微信客户端的，微信SDK发的是sha1

**Comment by YuiFx** [comment]
我尝试了下，在服务端按照sha1加密，终是返回签名错误，所以不清楚里面的加密逻辑，服务端的是按照key排序后凭借apikey做的md5加密，我猜想key的值不一直导致的，sdk里面的key值全部都是小写，然后你的例子中URL的每一个key都是驼峰标示的
